version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.yml:/etc/promtail/docker-config.yml:ro
    command: -config.file=/etc/promtail/docker-config.yml
