name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: lost-and-found-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker compose build
  deploy:
    runs-on: lost-and-found-runner
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          cd ${{ secrets.PRODUCTION_FOLDER }}
          docker compose --env-file .env up -d
